### ISSUE TITLE
Managed deployment no longer valid?

### ISSUE THREAD

**Issue by ozskywalker** [AlchimiaMx/jira-connectors#1]
Tried to access the managed deployment of this jira connector, but received this error message:

> The linked connectorId was invalid. Check the connectorId and try again.

Has the managed deployment been removed?

**Comment by LuisEnVilla** [comment]
Sorry for the delay, we are still using this connector, but Google has not validated it yet, so I have to share the rights of the project, I attach the [Apps Script](https://script.google.com/d/1IePZttHarA0VenyWJmWL-wQoPKlQvJ1uBkgfiRB_va2lPH-GVtCngkuH/edit?usp=sharing) link to be able to implement it, or this [guide](https://developers.google.com/datastudio/connector/use) details how to create your connector based on our code.

Thanks for your observation, we update the Readme file to notify everyone who wants to use the connector
